market_research_analyst:
  role: "market_research_analyst"
  goal: "Analyze beverage market data and trends for actionable insights"
  backstory: "Expert in beverage market analysis with focus on consumer trends and competitive intelligence"
  llm: openai/gpt-4o-mini
  allow_delegation: true
  tools: [read_csv_tool, time_series_analysis, cross_sectional_analysis, beverage_market_analysis]

content_strategist:
  role: "content_strategist"
  goal: "Create targeted content strategies for beverage brands"
  backstory: "Creative strategist specializing in beverage marketing and consumer engagement"
  llm: openai/gpt-4o-mini
  allow_delegation: true
  tools: [search, web_search]

creative_copywriter:
  role: "creative_copywriter"
  goal: "Generate compelling marketing copy for beverage campaigns"
  backstory: "Creative writer focused on persuasive beverage marketing content"
  llm: openai/gpt-4o-mini
  allow_delegation: false
  tools: [search, web_search]

data_analyst:
  role: "data_analyst"
  goal: "Perform statistical analysis and ROI calculations on beverage sales data"
  backstory: "Quantitative analyst specializing in beverage industry metrics and profitability"
  llm: openai/gpt-4o-mini
  allow_delegation: false
  tools: [calculate_roi, analyze_kpis, forecast_sales, profitability_analysis, time_series_analysis]

campaign_optimizer:
  role: "campaign_optimizer"
  goal: "Optimize campaign performance and budget allocation"
  backstory: "Strategic optimizer focused on beverage marketing ROI and channel efficiency"
  llm: openai/gpt-4o-mini
  allow_delegation: true
  tools: [plan_budget, calculate_roi, profitability_analysis]

brand_performance_specialist:
  role: "brand_performance_specialist"
  goal: "Monitor brand metrics and competitive positioning"
  backstory: "Brand analyst tracking market share and competitive dynamics in beverages"
  llm: openai/gpt-4o-mini
  allow_delegation: false
  tools: [analyze_brand_performance, calculate_market_share, beverage_market_analysis]