research_task:
  description: "Conduct comprehensive market research on the beverage industry, focusing on trends, consumer preferences, and competitive landscape for {target_audience}. Analyze the provided sales data from {data_file_path} to understand current market performance. Use time series analysis and cross-sectional analysis tools to identify patterns, trends, and regional differences. Focus on {product_lines} products and {market_segments} regions. Identify key opportunities and threats in the {competitive_landscape}."
  expected_output: "A detailed market research report with data-driven insights, trend analysis, regional performance comparison, and strategic recommendations for the beverage market."
  agent: "market_research_analyst"

strategy_task:
  description: "Develop a content strategy for a new line of organic beverages. The strategy should target health-conscious millennials and include recommendations for social media, blog content, and influencer collaborations."
  expected_output: "A comprehensive content strategy document."
  agent: "content_strategist"

copywriting_task:
  description: "Write compelling copy for a series of social media posts to promote the new organic beverage line. The copy should be engaging, persuasive, and tailored to the target audience."
  expected_output: "A set of social media posts ready for publication."
  agent: "creative_copywriter"

data_analysis_task:
  description: "Analyze the provided beverage sales data from {data_file_path} to identify sales patterns, top-performing products, and regional performance. Use time series analysis and cross-sectional analysis tools to examine trends over time and compare performance across regions (North vs South) and products (Green Tea vs Latte). Calculate key metrics including sales forecasts, growth rates, and performance indicators."
  expected_output: "A comprehensive data analysis report with key findings, statistical insights, sales forecasts, and actionable recommendations based on the beverage sales data."
  agent: "data_analyst"

optimization_task:
  description: "Based on the market research and data analysis results, provide comprehensive recommendations for optimizing the marketing campaign for the beverage line targeting {target_audience}. Use the budget planning and ROI calculation tools to create optimal budget allocation across channels. Consider the {budget} total budget and {duration} campaign duration. Focus on {campaign_goals} and provide specific recommendations for improving performance in underperforming regions and products."
  expected_output: "A comprehensive optimization strategy with budget allocation recommendations, channel focus suggestions, ROI projections, and specific action plans for campaign improvement."
  agent: "campaign_optimizer"

brand_performance_task:
  description: "Monitor and report on the brand performance of the new beverage line after the first quarter of launch. Track key metrics such as brand awareness, customer sentiment, and market share."
  expected_output: "A brand performance report with key metrics and analysis."
  agent: "brand_performance_specialist"
